const $ = (s) => document.querySelector(s); let assets = [], selectedId = null;
const esc = (v) => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const bytes = (n) => n > 1048576 ? `${(n/1048576).toFixed(2)} MB` : `${Math.ceil(n/1024)} KB`;
const tags = (value) => String(value || '').split(',').map(x => x.trim()).filter(Boolean).slice(0,8);
function options(el, blank=false) { el.innerHTML = `${blank?'<option value="">作为新分支</option>':''}${assets.map(a=>`<option value="${a.id}">#${a.id} · ${esc(a.title)}</option>`).join('')}`; }
function detail(a) { if(!a)return; selectedId=a.id; const editable = !a.is_seed && a.storage_kind !== 'reference'; const source=a.source_url?`<div class="source-record"><b>来源与许可</b><span>${esc(a.source_credit)}</span><span>${esc(a.source_license)}</span><a href="${a.source_url}" target="_blank" rel="noreferrer">打开原始来源 ↗</a></div>`:''; $('#detail').innerHTML=`<img class="detail-image" src="${a.url}" alt=""><p class="eyebrow">${a.storage_kind==='reference'?'PUBLIC REFERENCE / NOT AUTHOR WORK':`ASSET #${String(a.id).padStart(3,'0')}`}</p><h2>${esc(a.title)}</h2><p>${esc(a.notes||'暂无创作注释。')}</p><div class="tag-list">${a.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="swatches">${a.colors.map(c=>`<span style="background:${c}"></span>`).join('')}</div><dl><div><dt>项目</dt><dd>${esc(a.project)}</dd></div><div><dt>尺寸</dt><dd>${a.width} × ${a.height}</dd></div><div><dt>文件</dt><dd>${bytes(a.bytes)} · ${a.mode}</dd></div><div><dt>相机/EXIF</dt><dd>${a.has_exif?'已读取基础字段':'未提供'}</dd></div><div><dt>来源关系</dt><dd>${a.parent_id?`派生自 #${a.parent_id}`:'独立根版本'}</dd></div></dl>${source}${editable?`<div class="record-actions"><button id="editRecord">编辑档案</button><button id="deleteRecord">删除版本</button></div>`:''}`; document.querySelectorAll('[data-id]').forEach(n=>n.classList.toggle('active',Number(n.dataset.id)===a.id)); if(editable){$('#editRecord').onclick=()=>edit(a);$('#deleteRecord').onclick=()=>remove(a);} }
function graph() { const kids=new Map(); assets.forEach(a=>{const k=a.parent_id||'root';kids.set(k,[...(kids.get(k)||[]),a]);}); const paint=(a)=>`<li><button class="lineage-node" data-id="${a.id}"><img src="${a.url}" alt=""><span>#${String(a.id).padStart(2,'0')} ${esc(a.title)}</span></button>${(kids.get(a.id)||[]).length?`<ul>${kids.get(a.id).map(paint).join('')}</ul>`:''}</li>`; $('#lineage').innerHTML=`<ul class="lineage-tree">${(kids.get('root')||[]).map(paint).join('')}</ul>`; }
function renderFilters(){const projects=[...new Set(assets.map(a=>a.project))], allTags=[...new Set(assets.flatMap(a=>a.tags))]; $('#projectFilter').innerHTML=`<option value="">全部项目</option>${projects.map(v=>`<option>${esc(v)}</option>`).join('')}`; $('#tagFilter').innerHTML=`<option value="">全部标签</option>${allTags.map(v=>`<option>${esc(v)}</option>`).join('')}`;}
function render(){ $('#assetList').innerHTML=assets.map(a=>`<button class="asset-card" data-id="${a.id}"><img src="${a.url}" alt=""><span><b>${esc(a.title)}</b><small>${esc(a.project)} · #${String(a.id).padStart(3,'0')}</small></span></button>`).join(''); graph(); $('#lineageCount').textContent=`${assets.length} RECORDS`; options($('#compareA'));options($('#compareB'));options($('#parentInput'),true); if(assets.length>1){$('#compareA').value=assets[0].id;$('#compareB').value=assets[assets.length-1].id;} document.querySelectorAll('[data-id]').forEach(n=>n.onclick=()=>detail(assets.find(a=>a.id===Number(n.dataset.id)))); detail(assets.find(a=>a.id===selectedId)||assets[0]); }
async function load(){const q=encodeURIComponent($('#searchInput').value),tag=encodeURIComponent($('#tagFilter').value),project=encodeURIComponent($('#projectFilter').value);const r=await fetch(`/api/assets?q=${q}&tag=${tag}&project=${project}`);assets=(await r.json()).assets;renderFilters();render();}
async function compare(){const a=$('#compareA').value,b=$('#compareB').value;if(!a||!b||a===b)return;const r=await fetch(`/api/compare?a=${a}&b=${b}`),d=await r.json();$('#compareResult').innerHTML=`<strong>${d.similarity}%</strong><span>视觉相似度信号 · ${esc(d.method)}</span><p>只比较低分辨率亮度结构，不能证明版权、作者或真实创作链路。</p>`;}
async function edit(a){const title=prompt('版本名称',a.title);if(title===null)return;const notes=prompt('创作注释',a.notes);if(notes===null)return;const r=await fetch(`/api/assets/${a.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,notes,tags:a.tags,project:a.project,parent_id:a.parent_id})});if(!r.ok)return alert((await r.json()).error);await load();}
async function remove(a){if(!confirm(`删除“${a.title}”？其子版本将成为根版本。`))return;const r=await fetch(`/api/assets/${a.id}`,{method:'DELETE'});if(!r.ok)return alert((await r.json()).error);selectedId=null;await load();}
async function exportReport(){const d=await (await fetch('/api/report')).json(),blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='creative-provenance-report.json';link.click();URL.revokeObjectURL(url);}
async function filesToPayload(files){return Promise.all([...files].map(file=>new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve({title:file.name.replace(/\.[^.]+$/,''),data_url:reader.result,parent_id:$('#parentInput').value?Number($('#parentInput').value):null,project:$('#projectInput').value,tags:tags($('#tagsInput').value),notes:$('#notesInput').value});reader.readAsDataURL(file);})));}
$('#openUpload').onclick=()=>$('#uploadDialog').showModal();$('#closeUpload').onclick=()=>$('#uploadDialog').close();$('#compareBtn').onclick=compare;$('#exportReport').onclick=exportReport;$('#searchInput').oninput=()=>load();$('#projectFilter').onchange=load;$('#tagFilter').onchange=load;
$('#uploadForm').onsubmit=async e=>{e.preventDefault();const files=$('#fileInput').files;if(!files.length)return;$('#uploadError').textContent='正在批量分析…';const r=await fetch('/api/assets/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assets:await filesToPayload(files)})}),d=await r.json();if(!r.ok){$('#uploadError').textContent=d.error||'导入失败';return;}$('#uploadDialog').close();$('#uploadForm').reset();selectedId=d.assets.at(-1)?.id||selectedId;await load();if(d.errors.length)alert(`${d.errors.length} 个文件未导入。`);};
load().catch(()=>{$('#assetList').innerHTML='<p>无法连接到档案服务。</p>';});
